// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetValue():Promise<string>;

export function SetValue(arg1:string):Promise<string>;
